### ISSUE TITLE
ESP32 can not work in softAP mode

### ISSUE THREAD

**Issue by jianwei-bai** [espressif/esp-hosted#8]
1. When I let ESP32  work in softAP mode, Can't succeed. The log is as follows:  How can I solve this issues? Thanks!
Rspi:
![image](https://user-images.githubusercontent.com/43465935/93571659-58180a00-f9c7-11ea-9661-fb36d2b97f23.png)

pi@raspberrypi:~/esp-hosted/host/linux/host_control $ python softap_config.py 'xyz' 'xyz123456' 1 3 --max_conn=4 --ssid_hidden=0 --bw=1
SoftAP MAC Address 30:ae:a4:c9:f2:ad
Traceback (most recent call last):
  File "softap_config.py", line 61, in <module>
    softap_config = commands.wifi_set_softap_config(args.ssid, args.password, args.channel_id, args.encrp_mthd, args.max_conn, args.ssid_hidden, args.bw)
  File "/home/pi/esp-hosted/host/linux/host_control/host_commands/commands.py", line 180, in wifi_set_softap_config
    if ecn < esp_hosted_config_pb2.EncryptionMode.Type_WPA3_PSK:
AttributeError: 'module' object has no attribute 'EncryptionMode'

ESP32:
![image](https://user-images.githubusercontent.com/43465935/93571609-48002a80-f9c7-11ea-8ab1-e7eb259a521f.png)

receive data from transport layer
receive data from transport layer
data ready 
receive data from transport layer
I (176440) slave_commands: get AP mac address
I (176450) slave_commands: mac [30:ae:a4:c9:f2:ad] 
data ready 
receive data from transport layer
I (676910) slave_commands: get AP mac address
I (676910) slave_commands: mac [30:ae:a4:c9:f2:ad]

**Comment by jianwei-bai** [comment]
1.When I configure ESP32 in station mode.
python station_connect.py 'moduletest' 'test1234'   This command works. But adding WPA3 will fail. What is the problem and how can I solve it, thank you!
Raspi:
![image](https://user-images.githubusercontent.com/43465935/93572629-b09bd700-f9c8-11ea-9f95-66220912377f.png)


ESP32:
![image](https://user-images.githubusercontent.com/43465935/93573083-4afc1a80-f9c9-11ea-8e7c-2f7eaeedc4f4.png)

2.Sometimes all commands are disabled on RASPi and no data is received on ESP32.When I reset ESP32, it works.Is the connection between ESP32 and Raspi unstable, or is it something else? It happens all the time.Looking forward to your reply.
![image](https://user-images.githubusercontent.com/43465935/93573344-94e50080-f9c9-11ea-961f-7820cb2f8d37.png)
![image](https://user-images.githubusercontent.com/43465935/93573655-fc02b500-f9c9-11ea-9c65-40c622524703.png)

**Comment by MangeshMalusare** [comment]
Thanks for reporting your issue. We will check both the issues and get back soon.

Meanwhile, can you please confirm if the AP in second issue support WPA3?
